import axios from 'axios';
import dotenv from 'dotenv';

dotenv.config();

export interface GenerateImageOptions {
  sourceImage?: string; // Uploaded room image
  prompt: string;       // Detailed architectural redesign prompt generated by Gemini
  negativePrompt?: string;
  roomType?: string;
  style?: string;
  colorTone?: string;
  aspectRatio?: '1:1' | '4:3' | '16:9';
  strength?: number;
  mode?: string;
  seed?: number;
}

export interface ImageGenerationResult {
  success: boolean;
  generatedImage: string | null;
  imageUrl: string | null;
  provider: string;
  model: string;
  warning?: string;
  error?: string;
  details?: string;
}

export class ImageGenerationService {
  // Primary Pollinations Image Edits API for true image-to-image editing
  public static readonly POLLINATIONS_EDITS_URL = 'https://gen.pollinations.ai/v1/images/edits';
  // Primary Pollinations GET endpoint
  public static readonly POLLINATIONS_BASE_URL = 'https://gen.pollinations.ai/image';
  // Open fallback endpoint
  public static readonly FALLBACK_POLLINATIONS_URL = 'https://image.pollinations.ai/prompt';

  public get apiKey(): string | null {
    return process.env.POLLINATIONS_API_KEY?.trim() || null;
  }

  public isConfigured(): boolean {
    return Boolean(this.apiKey);
  }

  public getProviderName(): string {
    return 'Pollinations AI (Image-to-Image Flux)';
  }

  /**
   * Determine exact dimensions based on selected aspect ratio
   */
  private getDimensions(aspectRatio?: '1:1' | '4:3' | '16:9'): { width: number; height: number } {
    if (aspectRatio === '16:9') {
      return { width: 1024, height: 576 };
    }
    if (aspectRatio === '1:1') {
      return { width: 1024, height: 1024 };
    }
    // Default 4:3 architectural room perspective
    return { width: 1024, height: 768 };
  }

  /**
   * Automatically detect aspect ratio and dimensions from sourceImage buffer so the
   * generated image preserves the exact visible framing, orientation, and boundaries
   * of the uploaded photo without expanding horizontally or vertically.
   */
  private detectDimensionsFromImage(sourceImage?: string, preferredAspectRatio?: '1:1' | '4:3' | '16:9'): { width: number; height: number } {
    if (sourceImage) {
      try {
        let buffer: Buffer | null = null;
        if (sourceImage.startsWith('data:')) {
          const base64Index = sourceImage.indexOf(';base64,');
          if (base64Index !== -1) {
            const b64 = sourceImage.slice(base64Index + 8, base64Index + 8 + 32768);
            buffer = Buffer.from(b64, 'base64');
          }
        }
        if (buffer && buffer.length > 24) {
          // PNG format check
          if (buffer[0] === 0x89 && buffer[1] === 0x50 && buffer[2] === 0x4e && buffer[3] === 0x47) {
            const w = buffer.readUInt32BE(16);
            const h = buffer.readUInt32BE(20);
            if (w > 0 && h > 0) return this.mapToFluxDimensions(w, h);
          }
          // JPEG format check
          if (buffer[0] === 0xff && buffer[1] === 0xd8) {
            let offset = 2;
            while (offset < buffer.length - 8) {
              if (buffer[offset] !== 0xff) break;
              const marker = buffer[offset + 1];
              if (marker === 0xc0 || marker === 0xc2) {
                const h = buffer.readUInt16BE(offset + 5);
                const w = buffer.readUInt16BE(offset + 7);
                if (w > 0 && h > 0) return this.mapToFluxDimensions(w, h);
              }
              const len = buffer.readUInt16BE(offset + 2);
              offset += 2 + len;
            }
          }
        }
      } catch {
        // Fall back to preferred aspect ratio
      }
    }
    return this.getDimensions(preferredAspectRatio);
  }

  private mapToFluxDimensions(origWidth: number, origHeight: number): { width: number; height: number } {
    const ratio = origWidth / origHeight;
    // 16:9 or ultra-wide landscape
    if (ratio >= 1.55) {
      return { width: 1024, height: 576 };
    }
    // Standard 4:3 or 3:2 landscape
    if (ratio >= 1.15) {
      return { width: 1024, height: 768 };
    }
    // Square (1:1)
    if (ratio >= 0.85 && ratio < 1.15) {
      return { width: 1024, height: 1024 };
    }
    // Standard 3:4 portrait (smartphone photo)
    if (ratio >= 0.65 && ratio < 0.85) {
      return { width: 768, height: 1024 };
    }
    // Tall 9:16 portrait
    return { width: 576, height: 1024 };
  }

  /**
   * Generates room images using Pollinations Flux API.
   * Endpoint: https://gen.pollinations.ai/image/{encodedPrompt}?model=flux
   * Authentication: Authorization: Bearer process.env.POLLINATIONS_API_KEY
   */
  public async generateImage(options: GenerateImageOptions): Promise<ImageGenerationResult> {
    const apiKey = this.apiKey;
    const { width, height } = this.detectDimensionsFromImage(options.sourceImage, options.aspectRatio);
    const seed = options.seed ?? Math.floor(Math.random() * 2147483647);

    // URL-encode the Gemini prompt properly
    const encodedPrompt = encodeURIComponent(options.prompt);

    const primaryUrl = `${ImageGenerationService.POLLINATIONS_BASE_URL}/${encodedPrompt}?model=flux&width=${width}&height=${height}&seed=${seed}&nologo=true`;
    const fallbackUrl = `${ImageGenerationService.FALLBACK_POLLINATIONS_URL}/${encodedPrompt}?model=flux&width=${width}&height=${height}&seed=${seed}&nologo=true`;

    console.log('=======================================================');
    console.log('[PollinationsService] Requesting IMAGE-TO-IMAGE EDIT from Pollinations Flux');
    console.log(`- Room Type: ${options.roomType || 'Unspecified'}`);
    console.log(`- Style: ${options.style || 'Unspecified'}`);
    console.log(`- Dimensions: ${width}x${height} (${options.aspectRatio || '4:3'})`);
    console.log(`- Seed: ${seed}`);
    console.log(`- Prompt Length: ${options.prompt.length} chars`);
    console.log(`- Has Source Image: ${Boolean(options.sourceImage)}`);
    console.log(`- Has POLLINATIONS_API_KEY: ${Boolean(apiKey)}`);
    console.log('=======================================================');

    // 1. If sourceImage is provided, prioritize TRUE IMAGE-TO-IMAGE EDITING via Pollinations Edits API
    if (options.sourceImage && apiKey) {
      try {
        console.log('[PollinationsService] Calling Pollinations Image-to-Image Edits API (/v1/images/edits)...');
        const t0 = Date.now();
        const editResponse = await axios.post(
          ImageGenerationService.POLLINATIONS_EDITS_URL,
          {
            image: options.sourceImage,
            prompt: options.prompt,
            model: 'flux',
          },
          {
            headers: {
              'Authorization': `Bearer ${apiKey}`,
              'Content-Type': 'application/json',
            },
            timeout: 55000,
            maxBodyLength: 20 * 1024 * 1024,
          }
        );

        console.log(`[PollinationsService] Image-to-Image edit completed in ${(Date.now() - t0) / 1000}s (Status: ${editResponse.status})`);
        const first = editResponse.data?.data?.[0];
        if (first?.b64_json) {
          const rawB64 = first.b64_json;
          const dataUrl = rawB64.startsWith('data:') ? rawB64 : `data:image/jpeg;base64,${rawB64}`;
          return {
            success: true,
            generatedImage: dataUrl,
            imageUrl: null,
            provider: 'Pollinations AI (Image-to-Image Flux)',
            model: 'flux',
          };
        } else if (first?.url) {
          return {
            success: true,
            generatedImage: first.url,
            imageUrl: first.url,
            provider: 'Pollinations AI (Image-to-Image Flux)',
            model: 'flux',
          };
        }
      } catch (editErr: any) {
        console.warn(
          '[PollinationsService] Image-to-Image Edits endpoint note (cascading to fallback):',
          editErr?.response?.status,
          editErr?.response?.data || editErr?.message
        );
      }
    }

    const headers: Record<string, string> = {
      'Accept': 'image/jpeg,image/png,image/*,*/*',
    };
    if (apiKey) {
      headers['Authorization'] = `Bearer ${apiKey}`;
    }

    try {
      // 2. GET endpoint fallback
      console.log(`[PollinationsService] Calling endpoint: ${primaryUrl.slice(0, 110)}...`);
      const response = await axios.get(primaryUrl, {
        headers,
        responseType: 'arraybuffer',
        timeout: 45000,
        maxRedirects: 5,
      });

      console.log('----------------------------------------------------');
      console.log(`[PollinationsService] Pollinations HTTP Status: ${response.status}`);
      console.log(`[PollinationsService] Pollinations Content-Type: ${response.headers['content-type']}`);
      console.log(`[PollinationsService] Pollinations Image Size: ${response.data.length} bytes`);
      console.log('----------------------------------------------------');

      const contentType = response.headers['content-type'] || 'image/jpeg';
      const base64 = Buffer.from(response.data).toString('base64');
      const dataUrl = `data:${contentType};base64,${base64}`;

      return {
        success: true,
        generatedImage: dataUrl,
        imageUrl: primaryUrl,
        provider: 'Pollinations AI',
        model: 'flux',
      };
    } catch (primaryErr: any) {
      const primaryStatus = primaryErr?.response?.status;
      const primaryData = primaryErr?.response?.data;
      const primaryMsg = primaryData
        ? (typeof primaryData === 'string'
            ? primaryData
            : Buffer.isBuffer(primaryData)
            ? Buffer.from(primaryData).toString('utf-8')
            : JSON.stringify(primaryData))
        : primaryErr?.message || String(primaryErr);

      console.log('----------------------------------------------------');
      console.log(`[PollinationsService] Primary HTTP Status: ${primaryStatus || 'Network error'}`);
      console.log(`[PollinationsService] Primary HTTP Response Body:`, primaryMsg);
      console.log('----------------------------------------------------');

      // 2. If 401 or no key set, also attempt open fallback endpoint
      if (primaryStatus === 401 || !apiKey) {
        console.log(`[PollinationsService] Attempting open Pollinations fallback endpoint...`);
        try {
          const fallbackRes = await axios.get(fallbackUrl, {
            responseType: 'arraybuffer',
            timeout: 45000,
            maxRedirects: 5,
          });

          console.log(`[PollinationsService] Fallback HTTP Status: ${fallbackRes.status}, Size: ${fallbackRes.data.length} bytes`);
          const contentType = fallbackRes.headers['content-type'] || 'image/jpeg';
          const base64 = Buffer.from(fallbackRes.data).toString('base64');
          const dataUrl = `data:${contentType};base64,${base64}`;

          return {
            success: true,
            generatedImage: dataUrl,
            imageUrl: fallbackUrl,
            provider: 'Pollinations AI',
            model: 'flux',
          };
        } catch (fallbackErr: any) {
          const fallbackStatus = fallbackErr?.response?.status;
          const fallbackData = fallbackErr?.response?.data;
          const fallbackMsg = fallbackData
            ? (typeof fallbackData === 'string'
                ? fallbackData
                : Buffer.isBuffer(fallbackData)
                ? Buffer.from(fallbackData).toString('utf-8')
                : JSON.stringify(fallbackData))
            : fallbackErr?.message || String(fallbackErr);

          console.log('----------------------------------------------------');
          console.log(`[PollinationsService] Fallback HTTP Status: ${fallbackStatus || 'Network error'}`);
          console.log(`[PollinationsService] Fallback HTTP Response Body:`, fallbackMsg);
          console.log('----------------------------------------------------');
        }
      }

      let userError = 'Pollinations image generation encountered an error. Please try again.';
      if (primaryStatus === 401) {
        userError =
          'Pollinations authentication failed: A valid POLLINATIONS_API_KEY is required. Please set POLLINATIONS_API_KEY in your AI Studio secrets or environment variables.';
      } else if (primaryStatus === 402) {
        userError =
          'Pollinations credit balance insufficient: Please recharge your Pollinations balance at enter.pollinations.ai.';
      } else if (primaryStatus === 429) {
        userError = 'Pollinations rate limit reached. Please wait a moment before trying again.';
      } else if (primaryMsg && primaryMsg.length < 200) {
        userError = `Pollinations error (${primaryStatus || 'network'}): ${primaryMsg}`;
      }

      return {
        success: false,
        generatedImage: null,
        imageUrl: null,
        provider: 'Pollinations AI',
        model: 'flux',
        error: userError,
        details: primaryMsg,
      };
    }
  }
}

export const imageGenerationService = new ImageGenerationService();
